version: '2'
services:
    q_quit-app:
        image: q_quit
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://q_quit-mysql:3302/q_quit?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    q_quit-mysql:
        extends:
            file: mysql.yml
            service: q_quit-mysql
